version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
    environment:
      POSTGRES_DB: "data"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build: .
    environment:
      GUNICORN_CONF: /app/custom_gunicorn_conf.py
    ports:
     - "8000:80"
    depends_on:
      - postgres
    restart: always

volumes:
  data: